// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 27/09/2025, 3:22:54 pm
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/USER/Desktop/Vibe Coding/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/Vibe Coding/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/Vibe Coding/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/Vibe Coding/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/Vibe Coding/plugins/**/*.{js,ts,mjs}","C:/Users/USER/Desktop/Vibe Coding/composables/**/*.{js,ts,mjs}","C:/Users/USER/Desktop/Vibe Coding/utils/**/*.{js,ts,mjs}","C:/Users/USER/Desktop/Vibe Coding/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/Vibe Coding/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/Vibe Coding/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/Vibe Coding/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;